// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pastebook_db.Data;

#nullable disable

namespace pastebook_db.Migrations
{
    [DbContext(typeof(PastebookContext))]
    [Migration("20231116153452_database-v0.03")]
    partial class databasev003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("pastebook_db.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlbumDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("pastebook_db.Models.AlbumImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("AlbumImages");
                });

            modelBuilder.Entity("pastebook_db.Models.AlbumImageComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlbumImageId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("User_FriendId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumImageId");

                    b.HasIndex("User_FriendId");

                    b.ToTable("AlbumImageComments");
                });

            modelBuilder.Entity("pastebook_db.Models.AlbumImageLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlbumImageId")
                        .HasColumnType("int");

                    b.Property<int>("User_FriendId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumImageId");

                    b.HasIndex("User_FriendId");

                    b.ToTable("AlbumImageLikes");
                });

            modelBuilder.Entity("pastebook_db.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("User_FriendId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("User_FriendId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("pastebook_db.Models.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("User_FriendId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("User_FriendId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("pastebook_db.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AlbumCommentId")
                        .HasColumnType("int");

                    b.Property<int?>("AlbumImageCommentId")
                        .HasColumnType("int");

                    b.Property<int?>("AlbumImageLikeId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FriendRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("HasSeen")
                        .HasColumnType("bit");

                    b.Property<int>("NotifType")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostCommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PostLikeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumImageCommentId");

                    b.HasIndex("AlbumImageLikeId");

                    b.HasIndex("FriendRequestId");

                    b.HasIndex("PostCommentId");

                    b.HasIndex("PostLikeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("pastebook_db.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("User_FriendId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("User_FriendId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("pastebook_db.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FriendId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("PostId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("pastebook_db.Models.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FriendId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("PostId");

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("pastebook_db.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pastebook_db.Models.AlbumImage", b =>
                {
                    b.HasOne("pastebook_db.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("pastebook_db.Models.AlbumImageComment", b =>
                {
                    b.HasOne("pastebook_db.Models.AlbumImage", "AlbumImage")
                        .WithMany()
                        .HasForeignKey("AlbumImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pastebook_db.Models.User", "User_Friend")
                        .WithMany()
                        .HasForeignKey("User_FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumImage");

                    b.Navigation("User_Friend");
                });

            modelBuilder.Entity("pastebook_db.Models.AlbumImageLike", b =>
                {
                    b.HasOne("pastebook_db.Models.AlbumImage", "AlbumImage")
                        .WithMany()
                        .HasForeignKey("AlbumImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pastebook_db.Models.User", "User_Friend")
                        .WithMany()
                        .HasForeignKey("User_FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumImage");

                    b.Navigation("User_Friend");
                });

            modelBuilder.Entity("pastebook_db.Models.Friend", b =>
                {
                    b.HasOne("pastebook_db.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("pastebook_db.Models.User", "User_Friend")
                        .WithMany("FriendList")
                        .HasForeignKey("User_FriendId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("User_Friend");
                });

            modelBuilder.Entity("pastebook_db.Models.FriendRequest", b =>
                {
                    b.HasOne("pastebook_db.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("pastebook_db.Models.User", "User_Friend")
                        .WithMany()
                        .HasForeignKey("User_FriendId");

                    b.Navigation("User");

                    b.Navigation("User_Friend");
                });

            modelBuilder.Entity("pastebook_db.Models.Notification", b =>
                {
                    b.HasOne("pastebook_db.Models.AlbumImageComment", "AlbumImageComment")
                        .WithMany()
                        .HasForeignKey("AlbumImageCommentId");

                    b.HasOne("pastebook_db.Models.AlbumImageLike", "AlbumImageLike")
                        .WithMany()
                        .HasForeignKey("AlbumImageLikeId");

                    b.HasOne("pastebook_db.Models.FriendRequest", "FriendRequest")
                        .WithMany()
                        .HasForeignKey("FriendRequestId");

                    b.HasOne("pastebook_db.Models.PostComment", "PostComment")
                        .WithMany()
                        .HasForeignKey("PostCommentId");

                    b.HasOne("pastebook_db.Models.PostLike", "PostLike")
                        .WithMany()
                        .HasForeignKey("PostLikeId");

                    b.HasOne("pastebook_db.Models.User", null)
                        .WithMany("NotificationList")
                        .HasForeignKey("UserId");

                    b.Navigation("AlbumImageComment");

                    b.Navigation("AlbumImageLike");

                    b.Navigation("FriendRequest");

                    b.Navigation("PostComment");

                    b.Navigation("PostLike");
                });

            modelBuilder.Entity("pastebook_db.Models.Post", b =>
                {
                    b.HasOne("pastebook_db.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pastebook_db.Models.User", "User_Friend")
                        .WithMany()
                        .HasForeignKey("User_FriendId");

                    b.Navigation("User");

                    b.Navigation("User_Friend");
                });

            modelBuilder.Entity("pastebook_db.Models.PostComment", b =>
                {
                    b.HasOne("pastebook_db.Models.Friend", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId");

                    b.HasOne("pastebook_db.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.Navigation("Friend");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("pastebook_db.Models.PostLike", b =>
                {
                    b.HasOne("pastebook_db.Models.Friend", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId");

                    b.HasOne("pastebook_db.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.Navigation("Friend");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("pastebook_db.Models.User", b =>
                {
                    b.Navigation("FriendList");

                    b.Navigation("NotificationList");
                });
#pragma warning restore 612, 618
        }
    }
}
